services:
  debezium-connect:
    image: debezium/connect:latest
    container_name: debezium-connect
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
    ports:
      - "8083:8083"
    networks:
      - local-network
    restart: unless-stopped

networks:
  local-network:
    external: true

    