overrides:
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=4.0.0 <5.0.5: '>=5.0.5'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.0'
  picomatch@<2.3.2: '>=2.3.2'
  socket.io-parser@>=4.0.0 <4.2.6: '>=4.2.6'
